### ISSUE TITLE
ios编译不过，求help

### ISSUE THREAD

**Issue by qilovehua** [BaiduMobileAnalysis/baidumobstat-react-native#29]
![image](https://user-images.githubusercontent.com/12076175/83627443-8238ee00-a5c9-11ea-8736-8bc511a7876a.png)

react-native link baidumobstat-react-native
ios安装按照步骤了，React/RCTDefines.h not found

react-native unlink baidumobstat-react-native后clean build folder
又报下面的错：
Undefined symbol: _OBJC_CLASS_$_BaiduMobStat

react-native: 0.61.5

**Comment by ZTXBEST** [comment]
> ![image](https://user-images.githubusercontent.com/12076175/83627443-8238ee00-a5c9-11ea-8736-8bc511a7876a.png)
> 
> react-native link baidumobstat-react-native
> ios安装按照步骤了，React/RCTDefines.h not found
> 
> react-native unlink baidumobstat-react-native后clean build folder
> 又报下面的错：
> Undefined symbol: _OBJC_CLASS_$_BaiduMobStat
> 
> react-native: 0.61.5

同求，我也是，你解决了吗

**Comment by qilovehua** [comment]
> > ![image](https://user-images.githubusercontent.com/12076175/83627443-8238ee00-a5c9-11ea-8736-8bc511a7876a.png)
> > react-native link baidumobstat-react-native
> > ios安装按照步骤了，React/RCTDefines.h not found
> > react-native unlink baidumobstat-react-native后clean build folder
> > 又报下面的错：
> > Undefined symbol: _OBJC_CLASS_$_BaiduMobStat
> > react-native: 0.61.5
> 
> 同求，我也是，你解决了吗

没有解决，我用react-native-amap3d了。
地图当时不能自定义marker的图标，直接放弃了。

**Comment by ZTXBEST** [comment]
> > > ![image](https://user-images.githubusercontent.com/12076175/83627443-8238ee00-a5c9-11ea-8736-8bc511a7876a.png)
> > > react-native link baidumobstat-react-native
> > > ios安装按照步骤了，React/RCTDefines.h not found
> > > react-native unlink baidumobstat-react-native后clean build folder
> > > 又报下面的错：
> > > Undefined symbol: _OBJC_CLASS_$_BaiduMobStat
> > > react-native: 0.61.5
> > 
> > 
> > 同求，我也是，你解决了吗
> 
> 没有解决，我用react-native-amap3d了。
> 地图当时不能自定义marker的图标，直接放弃了。

这个是百度移动统计，不是地图啊。

**Comment by qilovehua** [comment]
> > > > ![image](https://user-images.githubusercontent.com/12076175/83627443-8238ee00-a5c9-11ea-8736-8bc511a7876a.png)
> > > > react-native link baidumobstat-react-native
> > > > ios安装按照步骤了，React/RCTDefines.h not found
> > > > react-native unlink baidumobstat-react-native后clean build folder
> > > > 又报下面的错：
> > > > Undefined symbol: _OBJC_CLASS_$_BaiduMobStat
> > > > react-native: 0.61.5
> > > 
> > > 
> > > 同求，我也是，你解决了吗
> > 
> > 
> > 没有解决，我用react-native-amap3d了。
> > 地图当时不能自定义marker的图标，直接放弃了。
> 
> 这个是百度移动统计，不是地图啊。

不好意思，看错了。
这个报错没解决，我自己手动集成了原生的，然后自己调他提供的api。

**Comment by qilovehua** [comment]
> > > > ![image](https://user-images.githubusercontent.com/12076175/83627443-8238ee00-a5c9-11ea-8736-8bc511a7876a.png)
> > > > react-native link baidumobstat-react-native
> > > > ios安装按照步骤了，React/RCTDefines.h not found
> > > > react-native unlink baidumobstat-react-native后clean build folder
> > > > 又报下面的错：
> > > > Undefined symbol: _OBJC_CLASS_$_BaiduMobStat
> > > > react-native: 0.61.5
> > > 
> > > 
> > > 同求，我也是，你解决了吗
> > 
> > 
> > 没有解决，我用react-native-amap3d了。
> > 地图当时不能自定义marker的图标，直接放弃了。
> 
> 这个是百度移动统计，不是地图啊。

不好意思，看错了。
这个报错没解决，我自己手动集成了原生的，然后自己调他提供的api。
